### ISSUE TITLE
Unable to use "Write..." keywords on mainframe session using lib version 2.7

### ISSUE THREAD

**Issue by otemek** [Altran-PT-GDC/Robot-Framework-Mainframe-3270-Library#14]
Hi
When I'm using version 2.6 everything goes smooth and fine. But when I've updated robotframework-Mainframe3270 to 2.7 version and whenever I try to use any "Write..." keyword. I'm getting error like: 
**TypeError: a bytes-like object is required, not 'str'**
I've google it and probalby it's somehow related to differencies between Python2/Python3 but don't know how to handle it.
Here's my sample test case:
```
*** Settings ***
Library    Mainframe3270    
*** Variables ***
${session} =    session
*** Test Cases ***
Login To MainFrame
    Open Connection    someserver
    Write In Position    ${session}    23    10
```

When i'm running it, using 2.6 i have: 
```
==============================================================================
FirstTest
==============================================================================
Login To MainFrame                                                    | PASS |
------------------------------------------------------------------------------
FirstTest                                                             | PASS |
1 critical test, 1 passed, 0 failed
1 test total, 1 passed, 0 failed
==============================================================================
```
Bu when i update lib to 2.7 I'm getting:
```
Exception ignored in: <function Emulator.__del__ at 0x0000017500EEA550>
Traceback (most recent call last):
  File "c:\mojeapps\python38\lib\site-packages\py3270\__init__.py", line 285, in __del__
    self.terminate()
  File "c:\mojeapps\python38\lib\site-packages\py3270\__init__.py", line 323, in terminate
    self.exec_command(b"Quit")
  File "c:\mojeapps\python38\lib\site-packages\py3270\__init__.py", line 308, in exec_command
    c.execute()
  File "c:\mojeapps\python38\lib\site-packages\py3270\__init__.py", line 68, in execute
    self.app.write(self.cmdstr + b"\n")
  File "c:\mojeapps\python38\lib\site-packages\py3270\__init__.py", line 237, in write
    raise NotConnectedException
py3270.NotConnectedException:
==============================================================================
FirstTest
==============================================================================
Login To MainFrame                                                    | FAIL |
TypeError: a bytes-like object is required, not 'str'
------------------------------------------------------------------------------
FirstTest                                                             | FAIL |
1 critical test, 0 passed, 1 failed
1 test total, 0 passed, 1 failed
==============================================================================

```
Any help?
Thanks in advance

**Comment by samuelpcabral** [comment]
Hi  @otemek what is your python version? and you are running in windows or linux? thanks!

**Comment by otemek** [comment]
Python 3.8.0 (tags/v3.8.0:fa919fd, Oct 14 2019, 19:37:50) [MSC v.1916 64 bit (AMD64)] on win32
Windows 10 x64, version: 1809

**Comment by samuelpcabral** [comment]
@otemek Plase update the library: `pip install --upgrade robotframework-mainframe3270`

We were unable to reproduce your exact error, but corrections were made in parts that had the same context. And release in version 2.8.

I run the following test in python 2.7, 3.7 and 3.8 and work in this three versions.

```
*** Settings ***
Library    Mainframe3270    

*** Variables ***
${text} =    test

*** Test Cases ***
Test Write
    Open Connection    pub400.com
    Wait Field detected
    Write Bare In Position    ${text}    5    25
    sleep    2
    Close Connection
```

**Comment by otemek** [comment]
thank you very much. Seems like version 2.8 works like a charm :)
